---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
data:
  PORT: "3009"
  CHAT_GRPC_PORT: "5009"
  MONGODB_URL_COURSE: "mongodb+srv://jacksoncheriyan05:MongoDBPassword@cluster0.oh2lv.mongodb.net/CourseDB"
  BUCKET_NAME: "dowhilelearn"
  AWS_REGION: "eu-north-1"
  CHAT_UPDATE: "chat.update"
  CHAT_ROLLBACK: "chat-service.rollback"
  CHAT_RESPONSE: "chat.response"
  CHAT_ROLLBACK_COMPLETED: "rollback-completed"
  CHAT_SERVICE_GROUP: "chat-service-group"
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-service-secrets
type: Opaque
data:
  MONGODB_URL_CHAT: "bW9uZ29kYitzcnY6Ly9qYWNrc29uY2hlcml5YW4wNTpNb25nb0RCUGFzc3dvcmRAY2x1c3RlcjAub2gybHYubW9uZ29kYi5uZXQvQ2hhdERC"
  AWS_ACCESS_KEY_ID: "QUtJQTRaUFpVNUxMR09SN0xLREM="
  AWS_SECRET_ACCESS_KEY: "OWk3Rm1GRGtFblNzSzVJeFRsRE5wdUFKSDJhbVo1dlNCMVFVcjRRdw=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: chat-service
 labels:
   app: chat-service
spec:
 replicas: 2
 selector:
   matchLabels:
     app: chat-service
 template:
   metadata:
     labels:
       app: chat-service
   spec:
     hostAliases:
     - ip: "172.17.0.1"
       hostnames:
       - "education-kafka"
     containers:
     - name: chat-service
       image: chat-service:latest
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 5009
         name: grpc
       - containerPort: 3009
         name: kafka
       envFrom:
       - configMapRef:
           name: chat-service-config
       - secretRef:
           name: chat-service-secrets
       resources:
         limits:
           memory: "512Mi"
           cpu: "500m"
         requests:
           memory: "256Mi"
           cpu: "250m"
       readinessProbe:
         tcpSocket:
           port: grpc
         initialDelaySeconds: 5
         periodSeconds: 10
       livenessProbe:
         tcpSocket:
           port: grpc
         initialDelaySeconds: 15
         periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: ClusterIP
  ports:
  - port: 5009
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 3009
    targetPort: kafka
    protocol: TCP
    name: kafka
  selector:
    app: chat-service